ages:
  10:
    jump: 3
    run: 1
  20:
    jump: 7
    run: 2
  30:
    jump: 15
    run: 3
  40:
    jump: 20
    run: 5
  50:
    jump: 34
    run: 7
  60:
    jump: 100
    run: 25

medicineRecipe: #9개까지만 가능
  - POINTED_DRIPSTONE
  - PUFFERFISH
  - DIAMOND_BLOCK
  - BLAZE_POWDER
  - AMETHYST_SHARD
  - POWDER_SNOW_BUCKET
  - POPPY
  - BONE_BLOCK
  - GHAST_TEAR

ageChangerRecipe: #9개까지만 가능
  - BREEZE_ROD
  - GOLDEN_APPLE
  - BLAZE_ROD
  - EMERALD_BLOCK
  - NAME_TAG
  - EMERALD_BLOCK
  - BLAZE_ROD
  - GOLDEN_APPLE
  - BREEZE_ROD